"""Agentic diagnostic pipeline with LLM-powered reasoning.

Chains MVPDR+ classification, severity estimation, and knowledge base
retrieval through an LLM agent that reasons about the diagnosis and
produces structured reports.

Backends (in priority order):
1. **Ollama** (default) — local, free, runs Qwen 3 8B or any model
   with tool-calling support.  No API key needed.
2. **Anthropic** — cloud-based Claude, requires ``ANTHROPIC_API_KEY``.
3. **Rule-based** — deterministic fallback, no LLM dependency.

Set ``MVPDR_AGENT_BACKEND`` to ``ollama``, ``anthropic``, or ``rule``
to force a specific backend.
"""

import json
import os
from dataclasses import asdict, dataclass, field
from typing import Optional

from mvpdr.knowledge import DiseaseKnowledgeBase
from mvpdr.severity import SEVERITY_LABELS, SeverityLevel, SeverityResult


# -----------------------------------------------------------------------
# Structured report schema
# -----------------------------------------------------------------------

@dataclass
class DifferentialDiagnosis:
    disease_name: str
    confidence: float
    reasoning: str


@dataclass
class TreatmentRecommendation:
    immediate: list[str]
    long_term: list[str]
    organic_alternatives: list[str]


@dataclass
class DiagnosticReport:
    disease_name: str
    confidence: float
    severity_level: str
    severity_score: float
    affected_area_percent: float
    treatment: TreatmentRecommendation
    differential_diagnosis: list[DifferentialDiagnosis]
    reasoning_chain: list[str]
    caveats: list[str]
    mode: str  # "ollama", "anthropic", or "rule_based"

    def to_dict(self) -> dict:
        return asdict(self)

    def to_json(self, indent: int = 2) -> str:
        return json.dumps(self.to_dict(), indent=indent)

    def to_markdown(self) -> str:
        md = []
        md.append("# Plant Disease Diagnostic Report")
        md.append("")
        md.append(f"**Diagnosis:** {self.disease_name}")
        md.append(f"**Confidence:** {self.confidence:.1%}")
        md.append(f"**Severity:** {self.severity_level} (score: {self.severity_score:.2f})")
        md.append(f"**Affected Area:** {self.affected_area_percent:.1f}%")
        md.append("")

        md.append("## Reasoning")
        for i, step in enumerate(self.reasoning_chain, 1):
            md.append(f"{i}. {step}")
        md.append("")

        md.append("## Treatment Plan")
        if self.treatment.immediate:
            md.append("### Immediate Actions")
            for t in self.treatment.immediate:
                md.append(f"- {t}")
        if self.treatment.long_term:
            md.append("### Long-term Management")
            for t in self.treatment.long_term:
                md.append(f"- {t}")
        if self.treatment.organic_alternatives:
            md.append("### Organic Alternatives")
            for t in self.treatment.organic_alternatives:
                md.append(f"- {t}")
        md.append("")

        if self.differential_diagnosis:
            md.append("## Differential Diagnosis")
            for dd in self.differential_diagnosis:
                md.append(f"- **{dd.disease_name}** ({dd.confidence:.1%}): {dd.reasoning}")
            md.append("")

        if self.caveats:
            md.append("## Important Caveats")
            for c in self.caveats:
                md.append(f"- {c}")
            md.append("")

        md.append(f"---\n*Generated by MVPDR+ Diagnostic Agent ({self.mode} mode)*")
        return "\n".join(md)


# -----------------------------------------------------------------------
# Tool definitions — OpenAI-compatible format (used by Ollama + Anthropic)
# -----------------------------------------------------------------------

TOOLS_OPENAI = [
    {
        "type": "function",
        "function": {
            "name": "get_classification_results",
            "description": (
                "Get the MVPDR+ classification results for the uploaded plant image. "
                "Returns top-k predicted diseases with confidence scores."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_severity_assessment",
            "description": (
                "Get the severity assessment for the detected disease. Uses GradCAM "
                "spatial coverage, classification confidence, and feature distance "
                "from healthy prototypes to estimate severity without labeled data."
            ),
            "parameters": {
                "type": "object",
                "properties": {},
                "required": [],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "lookup_disease_info",
            "description": (
                "Look up detailed information about a plant disease from the "
                "knowledge base, including pathogen type, symptoms at different "
                "severity levels, and environmental risk factors."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "disease_name": {
                        "type": "string",
                        "description": "Name of the disease to look up.",
                    },
                },
                "required": ["disease_name"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "get_treatment_protocol",
            "description": (
                "Get the recommended treatment protocol for a disease at a "
                "specific severity level. Includes chemical, biological, and "
                "cultural treatment options."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "disease_name": {
                        "type": "string",
                        "description": "Name of the disease.",
                    },
                    "severity": {
                        "type": "string",
                        "enum": ["mild", "moderate", "severe"],
                        "description": "Current severity level.",
                    },
                },
                "required": ["disease_name", "severity"],
            },
        },
    },
    {
        "type": "function",
        "function": {
            "name": "submit_diagnostic_report",
            "description": (
                "Submit the final structured diagnostic report. Call this after "
                "analyzing classification results, severity, and treatment options."
            ),
            "parameters": {
                "type": "object",
                "properties": {
                    "disease_name": {"type": "string"},
                    "confidence": {"type": "number"},
                    "severity_level": {
                        "type": "string",
                        "enum": ["Healthy", "Mild", "Moderate", "Severe"],
                    },
                    "severity_score": {"type": "number"},
                    "affected_area_percent": {"type": "number"},
                    "immediate_treatments": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "long_term_treatments": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "organic_alternatives": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "differential_diagnosis": {
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "disease_name": {"type": "string"},
                                "confidence": {"type": "number"},
                                "reasoning": {"type": "string"},
                            },
                        },
                    },
                    "reasoning_chain": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                    "caveats": {
                        "type": "array",
                        "items": {"type": "string"},
                    },
                },
                "required": [
                    "disease_name", "confidence", "severity_level",
                    "reasoning_chain",
                ],
            },
        },
    },
]

# Anthropic uses a different tool format
TOOLS_ANTHROPIC = [
    {
        "name": t["function"]["name"],
        "description": t["function"]["description"],
        "input_schema": t["function"]["parameters"],
    }
    for t in TOOLS_OPENAI
]

AGENT_SYSTEM_PROMPT = """\
You are an expert plant pathologist AI assistant integrated into the MVPDR+ \
diagnostic system. Your role is to analyze plant disease classification results \
and produce a thorough, actionable diagnostic report.

Workflow:
1. Call get_classification_results to see what diseases were detected and their \
confidence scores.
2. Call get_severity_assessment to understand how severe the infection appears.
3. For the top prediction (and any close alternatives), call lookup_disease_info \
to get detailed disease information.
4. Call get_treatment_protocol with the predicted disease and severity level.
5. Synthesize everything into a diagnostic report using submit_diagnostic_report.

When reasoning:
- Consider whether the confidence level warrants a definitive diagnosis or \
whether multiple diseases should be listed as possibilities.
- Factor in severity evidence (GradCAM coverage, confidence patterns).
- Provide practical, actionable treatment recommendations.
- Always include caveats about AI limitations and when to consult a \
professional agronomist.
- If confidence is below 50%, emphasize uncertainty prominently.
"""


# -----------------------------------------------------------------------
# Diagnostic context (passed to tool handlers)
# -----------------------------------------------------------------------

@dataclass
class DiagnosticContext:
    """Holds all inference results for the agent's tool calls."""
    classnames: list[str] = field(default_factory=list)
    top_predictions: list[tuple[str, float]] = field(default_factory=list)
    severity: Optional[SeverityResult] = None
    knowledge_base: Optional[DiseaseKnowledgeBase] = None


def _handle_tool_call(tool_name: str, tool_input: dict, ctx: DiagnosticContext) -> str:
    if tool_name == "get_classification_results":
        results = []
        for name, conf in ctx.top_predictions:
            results.append({"disease": name, "confidence": round(conf, 4)})
        return json.dumps({"predictions": results})

    elif tool_name == "get_severity_assessment":
        if ctx.severity is None:
            return json.dumps({"error": "Severity assessment not available"})
        return json.dumps({
            "level": ctx.severity.label,
            "score": round(ctx.severity.score, 4),
            "evidence": ctx.severity.evidence,
        })

    elif tool_name == "lookup_disease_info":
        disease_name = tool_input.get("disease_name", "")
        if ctx.knowledge_base is None:
            return json.dumps({"error": "Knowledge base not loaded"})
        info = ctx.knowledge_base.fuzzy_lookup(disease_name)
        if info is None:
            return json.dumps({"error": f"Disease '{disease_name}' not found"})
        return json.dumps({
            "common_name": info.common_name,
            "scientific_name": info.scientific_name,
            "pathogen_type": info.pathogen_type,
            "affected_crops": info.affected_crops,
            "symptoms": info.symptoms,
            "environmental_risk": info.environmental_risk,
        })

    elif tool_name == "get_treatment_protocol":
        disease_name = tool_input.get("disease_name", "")
        severity = tool_input.get("severity", "moderate")
        if ctx.knowledge_base is None:
            return json.dumps({"error": "Knowledge base not loaded"})
        plan = ctx.knowledge_base.get_treatment_plan(disease_name, severity)
        if plan is None:
            return json.dumps({"error": f"No treatment for '{disease_name}'"})
        return json.dumps({
            "disease": plan.disease.common_name,
            "severity": plan.severity_level,
            "urgency": plan.urgency,
            "symptoms_at_level": plan.symptoms_at_level,
            "chemical": plan.chemical_treatments,
            "biological": plan.biological_treatments,
            "cultural": plan.cultural_treatments,
            "prevention": plan.prevention,
        })

    return json.dumps({"error": f"Unknown tool: {tool_name}"})


def _parse_agent_report(tool_input: dict, mode: str = "ollama") -> DiagnosticReport:
    """Convert a submit_diagnostic_report tool call into a report."""
    differentials = []
    for dd in tool_input.get("differential_diagnosis", []):
        if isinstance(dd, dict):
            differentials.append(DifferentialDiagnosis(
                disease_name=dd.get("disease_name", "Unknown"),
                confidence=dd.get("confidence", 0.0),
                reasoning=dd.get("reasoning", ""),
            ))

    return DiagnosticReport(
        disease_name=tool_input.get("disease_name", "Unknown"),
        confidence=tool_input.get("confidence", 0.0),
        severity_level=tool_input.get("severity_level", "Unknown"),
        severity_score=tool_input.get("severity_score", 0.0),
        affected_area_percent=tool_input.get("affected_area_percent", 0.0),
        treatment=TreatmentRecommendation(
            immediate=tool_input.get("immediate_treatments", []),
            long_term=tool_input.get("long_term_treatments", []),
            organic_alternatives=tool_input.get("organic_alternatives", []),
        ),
        differential_diagnosis=differentials,
        reasoning_chain=tool_input.get("reasoning_chain", []),
        caveats=tool_input.get("caveats", [
            "This is an AI-generated assessment and should not replace "
            "professional agronomic advice.",
        ]),
        mode=mode,
    )


# -----------------------------------------------------------------------
# Entry point — auto-selects backend
# -----------------------------------------------------------------------

def run_agentic_diagnosis(ctx: DiagnosticContext) -> DiagnosticReport:
    """Run the diagnostic pipeline with the best available backend.

    Selection order:
    1. ``MVPDR_AGENT_BACKEND`` env var (``ollama`` / ``anthropic`` / ``rule``)
    2. Ollama (if ``ollama`` Python package is installed)
    3. Anthropic (if ``anthropic`` is installed and ``ANTHROPIC_API_KEY`` set)
    4. Rule-based fallback

    Args:
        ctx: DiagnosticContext with classification and severity results.

    Returns:
        DiagnosticReport with reasoning chain.
    """
    forced = os.environ.get("MVPDR_AGENT_BACKEND", "").strip().lower()

    if forced == "rule":
        return _rule_based_diagnosis(ctx)
    if forced == "anthropic":
        return _run_anthropic(ctx)
    if forced == "ollama":
        return _run_ollama(ctx)

    # Auto-detect: try Ollama first, then Anthropic, then rule-based
    report = _run_ollama(ctx)
    if report is not None:
        return report

    report = _run_anthropic(ctx)
    if report is not None:
        return report

    return _rule_based_diagnosis(ctx)


# -----------------------------------------------------------------------
# Ollama backend (local, free — default)
# -----------------------------------------------------------------------

def _run_ollama(ctx: DiagnosticContext) -> Optional[DiagnosticReport]:
    """Run diagnosis via Ollama (local LLM with tool-calling).

    Default model: ``qwen3:8b``.  Override with ``OLLAMA_MODEL`` env var.
    Default host: ``http://localhost:11434``.  Override with ``OLLAMA_HOST``.
    """
    try:
        import ollama
    except ImportError:
        return None

    model = os.environ.get("OLLAMA_MODEL", "qwen3:8b")
    host = os.environ.get("OLLAMA_HOST", None)

    client_kwargs = {}
    if host:
        client_kwargs["host"] = host
    client = ollama.Client(**client_kwargs)

    # Check model is available
    try:
        client.show(model)
    except Exception:
        return None

    messages = [
        {"role": "system", "content": AGENT_SYSTEM_PROMPT},
        {
            "role": "user",
            "content": (
                "Analyze this plant image and produce a diagnostic report. "
                "Use the available tools to gather classification results, "
                "severity assessment, disease information, and treatment "
                "protocols. Then submit a complete diagnostic report."
            ),
        },
    ]

    max_turns = 10
    try:
        for _ in range(max_turns):
            response = client.chat(
                model=model,
                messages=messages,
                tools=TOOLS_OPENAI,
            )

            msg = response.message
            tool_calls = msg.tool_calls or []

            if not tool_calls:
                break

            messages.append(msg.model_dump())

            submit_input = None
            for tc in tool_calls:
                fn_name = tc.function.name
                fn_args = tc.function.arguments or {}
                if isinstance(fn_args, str):
                    try:
                        fn_args = json.loads(fn_args)
                    except json.JSONDecodeError:
                        fn_args = {}

                if fn_name == "submit_diagnostic_report":
                    submit_input = fn_args
                    result_str = '{"status": "accepted"}'
                else:
                    result_str = _handle_tool_call(fn_name, fn_args, ctx)

                messages.append({
                    "role": "tool",
                    "content": result_str,
                })

            if submit_input is not None:
                return _parse_agent_report(submit_input, mode="ollama")

    except Exception:
        return None

    return None


# -----------------------------------------------------------------------
# Anthropic backend (cloud, requires API key)
# -----------------------------------------------------------------------

def _run_anthropic(ctx: DiagnosticContext) -> Optional[DiagnosticReport]:
    """Run diagnosis via Anthropic Claude API."""
    api_key = os.environ.get("ANTHROPIC_API_KEY", "").strip()
    if not api_key:
        return None

    try:
        import anthropic
    except ImportError:
        return None

    model = os.environ.get("ANTHROPIC_MODEL", "claude-sonnet-4-6")
    client = anthropic.Anthropic(api_key=api_key)

    messages = [
        {
            "role": "user",
            "content": (
                "Analyze this plant image and produce a diagnostic report. "
                "Use the available tools to gather classification results, "
                "severity assessment, disease information, and treatment "
                "protocols. Then submit a complete diagnostic report."
            ),
        }
    ]

    max_turns = 10
    try:
        for _ in range(max_turns):
            response = client.messages.create(
                model=model,
                max_tokens=4096,
                system=AGENT_SYSTEM_PROMPT,
                tools=TOOLS_ANTHROPIC,
                messages=messages,
            )

            if response.stop_reason == "end_turn":
                break

            tool_results = []
            has_tool_use = False
            submit_input = None

            for block in response.content:
                if block.type == "tool_use":
                    has_tool_use = True

                    if block.name == "submit_diagnostic_report":
                        submit_input = block.input
                        tool_results.append({
                            "type": "tool_result",
                            "tool_use_id": block.id,
                            "content": '{"status": "accepted"}',
                        })
                    else:
                        result = _handle_tool_call(block.name, block.input, ctx)
                        tool_results.append({
                            "type": "tool_result",
                            "tool_use_id": block.id,
                            "content": result,
                        })

            if submit_input is not None:
                return _parse_agent_report(submit_input, mode="anthropic")

            if not has_tool_use:
                break

            messages.append({"role": "assistant", "content": response.content})
            messages.append({"role": "user", "content": tool_results})
    except Exception:
        return None

    return None


# -----------------------------------------------------------------------
# Rule-based fallback (no LLM needed)
# -----------------------------------------------------------------------

def _rule_based_diagnosis(ctx: DiagnosticContext) -> DiagnosticReport:
    """Produce a diagnostic report without an LLM — deterministic rules."""
    if not ctx.top_predictions:
        return DiagnosticReport(
            disease_name="Unknown",
            confidence=0.0,
            severity_level="Unknown",
            severity_score=0.0,
            affected_area_percent=0.0,
            treatment=TreatmentRecommendation([], [], []),
            differential_diagnosis=[],
            reasoning_chain=["No classification results available."],
            caveats=["Unable to produce a diagnosis without classification results."],
            mode="rule_based",
        )

    top_name, top_conf = ctx.top_predictions[0]
    reasoning = [
        f"MVPDR+ top prediction: {top_name} with {top_conf:.1%} confidence.",
    ]

    severity_level = "Unknown"
    severity_score = 0.0
    affected_pct = 0.0

    if ctx.severity is not None:
        severity_level = ctx.severity.label
        severity_score = ctx.severity.score
        affected_pct = ctx.severity.gradcam_coverage * 100
        reasoning.append(
            f"Severity estimated as {severity_level} "
            f"(score={severity_score:.2f}, "
            f"GradCAM coverage={affected_pct:.1f}%)."
        )

    treatment = TreatmentRecommendation([], [], [])
    if ctx.knowledge_base is not None:
        severity_key = severity_level.lower()
        if severity_key not in ("mild", "moderate", "severe"):
            severity_key = "moderate"

        plan = ctx.knowledge_base.get_treatment_plan(top_name, severity_key)
        if plan is not None:
            treatment = TreatmentRecommendation(
                immediate=plan.chemical_treatments[:2] + plan.cultural_treatments[:1],
                long_term=plan.prevention,
                organic_alternatives=plan.biological_treatments,
            )
            reasoning.append(
                f"Retrieved treatment protocol for {plan.disease.common_name} "
                f"({plan.disease.scientific_name}, {plan.disease.pathogen_type})."
            )
        else:
            reasoning.append(f"No knowledge base entry found for '{top_name}'.")

    differentials = []
    for name, conf in ctx.top_predictions[1:4]:
        if conf >= 0.05:
            differentials.append(DifferentialDiagnosis(
                disease_name=name,
                confidence=conf,
                reasoning=f"Secondary prediction at {conf:.1%} confidence.",
            ))

    if top_conf < 0.5:
        reasoning.append(
            "Low confidence — consider this a preliminary assessment only."
        )

    caveats = [
        "This is an AI-generated assessment and should not replace "
        "professional agronomic advice.",
        "Diagnosis accuracy depends on image quality and the specific "
        "disease presentation.",
    ]
    if top_conf < 0.3:
        caveats.append(
            "Very low confidence in the prediction. Strongly recommend "
            "manual inspection by an expert."
        )

    return DiagnosticReport(
        disease_name=top_name,
        confidence=top_conf,
        severity_level=severity_level,
        severity_score=severity_score,
        affected_area_percent=affected_pct,
        treatment=treatment,
        differential_diagnosis=differentials,
        reasoning_chain=reasoning,
        caveats=caveats,
        mode="rule_based",
    )
